project:
  type: website
  output-dir: docs

website:
  title: "Deep Learning by HRM"
  search: false
  navbar:
    style: "floating"
    pinned: false
    tools:
      - icon: youtube
        href: https://twitter.com

  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - text: "AboutMe"
        href: about.qmd
      - section: "Week1 - Perceptron"
        contents:
          - index.qmd
          - test.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - test2.qmd
          - layout-jupyter.qmd
      - section: advanced.qmd
        contents:
          - raw-code.qmd
          - custom-theme.qmd
      - acknowlegment.qmd
      

format:
  html:
    theme: 
      light: simplex
      dark: sketchy
    css: styles.css
    toc: true



